/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.FavoritoDAO;
import dao.ListaDAO;
import model.Conta;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Filme;
import model.Serie;
import model.Video;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USer
 */
public class Listas extends javax.swing.JFrame {
    
    private Conta conta;
    
    private ArrayList<Video> favoritosAtual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Listas.class.getName());

    /**
     * Creates new form Listas
     */
    public Listas(Conta conta) {
        initComponents();
        this.conta = conta;
        
        carregarFavoritos();
        carregarListas();
    }

   
    
    public void carregarFavoritos() {

    Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        FavoritoDAO dao = new FavoritoDAO(conn);

        ResultSet rs = dao.listarFavoritos(conta.getId());

        DefaultListModel<String> model = new DefaultListModel<>();

        this.favoritosAtual = new ArrayList<>(); // <- FIX PRINCIPAL

        while (rs.next()) {

            int id = rs.getInt("id");
            String titulo = rs.getString("titulo");
            int duracao = rs.getInt("duracao");
            String tipo = rs.getString("tipo");
            String genero = rs.getString("genero");
            int ano = rs.getInt("ano_lancamento");

            Video v;

            if (tipo.equals("filme")) {
                v = new Filme(id, titulo, duracao, genero, ano);
            } else {
                v = new Serie(id, titulo, duracao, genero, ano);
            }

            this.favoritosAtual.add(v); 

            model.addElement(v.getTitulo());
        }

        listaFavoritos.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    public void carregarListas() {

    Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        ListaDAO dao = new ListaDAO(conn);

        ResultSet rs =
            dao.listarListas(conta.getId());

        DefaultListModel<String> model =
            new DefaultListModel<>();

        while (rs.next()) {

            String nome =
                rs.getString("nome");

            model.addElement(nome);
        }

        listaListas.setModel(model);

    } catch (Exception e) {

        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFavoritos = new javax.swing.JList<>();
        btCriar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaListas = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaLista = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btRecarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Lista de Reprodução");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Crie listas de seus vídeos favoritos!");

        jScrollPane1.setViewportView(listaFavoritos);

        btCriar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btCriar.setText("Criar");
        btCriar.addActionListener(this::btCriarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Lista de Vídeos Favoritados");

        listaListas.addListSelectionListener(this::listaListasValueChanged);
        jScrollPane2.setViewportView(listaListas);

        areaLista.setColumns(20);
        areaLista.setRows(5);
        jScrollPane3.setViewportView(areaLista);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Listas");

        btExcluir.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(this::btExcluirActionPerformed);

        btAdd.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btAdd.setText("Adcione um Vídeo");
        btAdd.addActionListener(this::btAddActionPerformed);

        btRemover.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btRemover.setText("Remova um Vídeo");
        btRemover.addActionListener(this::btRemoverActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Edite as Listas!");

        btVoltar.setText("◀️");
        btVoltar.addActionListener(this::btVoltarActionPerformed);

        btRecarregar.setText("🔃");
        btRecarregar.addActionListener(this::btRecarregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btRecarregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
     Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        ListaDAO dao = new ListaDAO(conn);

        int quantidade =
            dao.contarListas(conta.getId());

        String nomeLista =
            "Lista " + (quantidade + 1);

        dao.criarLista(
            conta.getId(),
            nomeLista
        );

        carregarListas();

        JOptionPane.showMessageDialog(
            this,
            "Lista criada!"
        );

    } catch (Exception e) {

        e.printStackTrace();
    }
    }//GEN-LAST:event_btCriarActionPerformed

    private void listaListasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaListasValueChanged
        // TODO add your handling code here:
        String selecionada =
        listaListas.getSelectedValue();

    if (selecionada != null) {

        Conexao conexao =
            new Conexao();
        try {

            Connection conn =
                conexao.getConnection();

            ListaDAO dao =
                new ListaDAO(conn);

            int listaId =
                dao.pegarIdLista(
                    selecionada,
                    conta.getId()
                );
            ResultSet rs =
                dao.listarVideosLista(listaId);

            areaLista.setText("");

            while (rs.next()) {

                areaLista.append(
                    rs.getInt("ordem") +
                    ". " +
                    rs.getString("titulo") +
                    "\n"
                );
            }
        } catch (Exception e) {

            e.printStackTrace();
        }
      }
    }//GEN-LAST:event_listaListasValueChanged

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        
        String selecionada =
        listaListas.getSelectedValue();

    if (selecionada != null) {

        Conexao conexao =
            new Conexao();

        try {

            Connection conn =
                conexao.getConnection();

            ListaDAO dao =
                new ListaDAO(conn);

            dao.excluirLista(
                conta.getId(),
                selecionada
            );

            carregarListas();

            areaLista.setText("");

            JOptionPane.showMessageDialog(
                this,
                "Lista excluída!"
            );

        } catch (Exception e) {

            e.printStackTrace();
        }
   }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        // TODO add your handling code here:
        String listaSelecionada =
        listaListas.getSelectedValue();

    if (listaSelecionada != null) {

        String titulo =
            JOptionPane.showInputDialog(
                this,
                "Digite o título do vídeo:"
            );

        if (titulo != null &&
            !titulo.isEmpty()) {

            Conexao conexao =
                new Conexao();

            try {

                Connection conn =
                    conexao.getConnection();

                ListaDAO dao =
                    new ListaDAO(conn);

                int listaId =
                    dao.pegarIdLista(
                        listaSelecionada,
                        conta.getId()
                    );

                dao.removerVideoLista(
                    listaId,
                    titulo
                );

                JOptionPane.showMessageDialog(
                    this,
                    "Vídeo removido!"
                );

            } catch (Exception e) {

                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        
        Video video =
        favoritosAtual.get(
            listaFavoritos.getSelectedIndex()
        );

    String listaSelecionada =
        listaListas.getSelectedValue();

    if (video != null &&
        listaSelecionada != null) {

        Conexao conexao =
            new Conexao();

        try {

            Connection conn =
                conexao.getConnection();

            ListaDAO dao =
                new ListaDAO(conn);

            int listaId =
                dao.pegarIdLista(
                    listaSelecionada,
                    conta.getId()
                );

            int ordem =
                dao.contarVideosLista(listaId) + 1;

            dao.adicionarVideoLista(
                listaId,
                video.getId(),
                ordem
            );

            JOptionPane.showMessageDialog(
                this,
                "Vídeo adicionado!"
            );

        } catch (Exception e) {

            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btAddActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        // TODO add your handling code here:
        Logado tela = new Logado(conta);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRecarregarActionPerformed
        // TODO add your handling code here:
        carregarFavoritos();
        carregarListas();
    }//GEN-LAST:event_btRecarregarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Listas().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLista;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btRecarregar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaFavoritos;
    private javax.swing.JList<String> listaListas;
    // End of variables declaration//GEN-END:variables
}
