/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.FavoritoDAO;
import dao.ListaDAO;
import model.Conta;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Filme;
import model.Serie;
import model.Video;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USer
 */
public class Listas extends javax.swing.JFrame {
    
    private Conta conta;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Listas.class.getName());

    /**
     * Creates new form Listas
     */
    public Listas(Conta conta) {
        initComponents();
        this.conta = conta;
        
        carregarFavoritos();
    }

   
    
    public void carregarFavoritos() {

    Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        FavoritoDAO dao = new FavoritoDAO(conn);

        ResultSet rs = dao.listarFavoritos(conta.getId());

        DefaultListModel<String> model = new DefaultListModel<>();

        ArrayList<Object> favoritosAtual = new ArrayList<>();

        while (rs.next()) {

            int id = rs.getInt("id");

            String titulo = rs.getString("titulo");

            int duracao = rs.getInt("duracao");

            String tipo = rs.getString("tipo");

            String genero = rs.getString("genero");

            int ano = rs.getInt("ano_lancamento");

            Video v;

            if (tipo.equals("filme")) {

                v = new Filme(id, titulo, duracao, genero, ano);

            } else {

                v = new Serie(id, titulo, duracao, genero, ano);
            }

            favoritosAtual.add(v);

            model.addElement(v.getTitulo());
        }

        listaFavoritos.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFavoritos = new javax.swing.JList<>();
        btCriar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Lista de Reprodução");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Crie listas de seus vídeos favoritos!");

        listaFavoritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaFavoritos);

        btCriar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btCriar.setText("Criar");
        btCriar.addActionListener(this::btCriarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Lista de Vídeos Favoritados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
    Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        ListaDAO dao = new ListaDAO(conn);

        int quantidade =
            dao.contarListas(conta.getId());

        String nomeLista =
            "Lista " + (quantidade + 1);

        dao.criarLista(
            conta.getId(),
            nomeLista
        );

        JOptionPane.showMessageDialog(
            this,
            "Lista criada!"
        );

    } catch (Exception e) {

        e.printStackTrace();
    }
    }//GEN-LAST:event_btCriarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Listas().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaFavoritos;
    // End of variables declaration//GEN-END:variables
}
