/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.FavoritoDAO;
import dao.VideoDAO;
import java.util.ArrayList;
import model.Conta;
import model.Video;
import java.sql.Connection;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USer
 */
public class MenuFavorito extends javax.swing.JFrame {
    
    private Conta conta;
    
    private ArrayList<Video> listaVideosAtual;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuFavorito.class.getName());

    /**
     * Creates new form MenuFavorito
     */
    public MenuFavorito(Conta conta) {
        initComponents();
        
        this.conta = conta;
        carregarVideos();
    }
    
    public void carregarVideos() {

    Conexao conexao = new Conexao();

    try {

        Connection conn = conexao.getConnection();

        VideoDAO dao = new VideoDAO(conn);

        ArrayList<Video> lista = dao.listar();
        
        listaVideosAtual = lista;

        ArrayList<Video> listaVideosAtual = lista;

        DefaultListModel<String> model = new DefaultListModel<>();

        for (Video v : lista) {

            model.addElement(v.getTitulo());
        }

        listaVideos.setModel(model);

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVideos = new javax.swing.JList<>();
        btDesfavoritar = new javax.swing.JButton();
        btFavoritar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Menu Favoritos");

        jScrollPane1.setViewportView(listaVideos);

        btDesfavoritar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btDesfavoritar.setText("Desfavoritar");
        btDesfavoritar.addActionListener(this::btDesfavoritarActionPerformed);

        btFavoritar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btFavoritar.setText("Favoritar");
        btFavoritar.addActionListener(this::btFavoritarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFavoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDesfavoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDesfavoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFavoritar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(287, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFavoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFavoritarActionPerformed
        // TODO add your handling code here:
    String selecionado = listaVideos.getSelectedValue();

    if (selecionado != null) {

        for (Video v : listaVideosAtual) {

            if (v.getTitulo().equals(selecionado)) {

                Conexao conexao = new Conexao();

                try {

                    Connection conn = conexao.getConnection();

                    FavoritoDAO dao = new FavoritoDAO(conn);

                    dao.adicionarFavorito(conta.getId(), v.getId());

                    JOptionPane.showMessageDialog(
                        this,
                        "Vídeo adicionado aos favoritos!"
                    );

                } catch (Exception e) {
                    e.printStackTrace();
                }

                break;
            }
        }
    }
    }//GEN-LAST:event_btFavoritarActionPerformed

    private void btDesfavoritarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesfavoritarActionPerformed
        // TODO add your handling code here:
    String selecionado = listaVideos.getSelectedValue();

    if (selecionado != null) {

        for (Video v : listaVideosAtual) {

            if (v.getTitulo().equals(selecionado)) {

                Conexao conexao = new Conexao();

                try {

                    Connection conn = conexao.getConnection();

                    FavoritoDAO dao = new FavoritoDAO(conn);

                    dao.removerFavorito(conta.getId(), v.getId());

                    JOptionPane.showMessageDialog(
                        this,
                        "Vídeo removido dos favoritos!"
                    );

                } catch (Exception e) {
                    e.printStackTrace();
                }

                break;
            }
        }
    }
    }//GEN-LAST:event_btDesfavoritarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MenuFavorito().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDesfavoritar;
    private javax.swing.JButton btFavoritar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaVideos;
    // End of variables declaration//GEN-END:variables
}
